# Generated by Django 2.0.6 on 2018-07-31 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('todolists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todolists', to='categories.Category'),
        ),
    ]
